Testing pipeline

diff --git a/.github/workflows/development_pipeline.yml b/.github/workflows/development_pipeline.yml
--- a/.github/workflows/development_pipeline.yml
+++ b/.github/workflows/development_pipeline.yml
@@ -34,25 +34,31 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    # - name: Use Node.js
-    #   uses: actions/setup-node@v3
-    #   with:
-    #     node-version: '18'
-    #     cache: 'npm'
-    #     cache-dependency-path: package-lock.json
+    - name: Use Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '18'
+        cache: 'npm'
+        cache-dependency-path: package-lock.json
 
-    # - name: Install dependencies
-    #   run: npm install
+    - name: Install dependencies
+      run: npm install
 
-    # - name: Start Express.js server
-    #   run: node server.js &
-    #   env:
-    #     NODE_ENV: test
+    - name: Start Express.js server
+      run: node server.js &
+      env:
+        NODE_ENV: test
 
-    # - name: Wait for server to be ready
-    #   run: |
-    #     echo "Waiting for server to start..."
-    #     sleep 10  # Adjust the sleep time if needed to ensure the server is ready
+    - name: Wait for server to be ready
+      run: |
+        npm start &
+        echo "Waiting for server to start..."
+        for i in `seq 1 60`; do
+          curl -sSf http://127.0.0.1:3005/health && echo "Server is up!" && exit 0
+          echo "Waiting..."
+          sleep 1
+        done
+        echo "Server failed to start" && exit 1
 
     - name: Install Newman
       run: npm install -g newman
