Testing pipeline

diff --git a/.github/workflows/development_pipeline.yml b/.github/workflows/development_pipeline.yml
--- a/.github/workflows/development_pipeline.yml
+++ b/.github/workflows/development_pipeline.yml
@@ -55,7 +55,12 @@ jobs:
     - name: Wait for server to be ready
       run: |
         echo "Waiting for server to start..."
-        sleep 10  # Adjust the sleep time if needed to ensure the server is ready
+        for i in `seq 1 60`; do
+          nc -zv 127.0.0.1 3005 && echo "Server is up!" && exit 0
+          echo "Waiting for server to start on port 3005..."
+          sleep 1
+        done
+        echo "Server failed to start" && exit 1
 
     - name: Run Postman integration tests
       run: newman run Postman/GenSoft.postman_collection.json
